"""empty message

Revision ID: 480074ae2422
Revises: 5fb1ead3ee11
Create Date: 2023-07-19 18:41:15.617436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480074ae2422'
down_revision = '5fb1ead3ee11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_session_token_key', type_='unique')
        batch_op.drop_column('session_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('users_session_token_key', ['session_token'])

    # ### end Alembic commands ###
